### PR TITLE
merge: Always close domain POT

### LINKED ISSUE #71: Merge command leaves domain POT file open
Tests raise this warning:

```
tests/test_merge.py::TestMergecommand::test_basic
  /home/travis/build/mozilla/puente/puente/commands.py:201: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-travis/pytest-0/test_basic0/locale/templates/LC_MESSAGES/django.pot' mode='r' encoding='UTF-8'>
    domain_pot_file = open(domain_pot)
```

My reading of the code is that when the locale is ``en_US``, the file is left open:

https://github.com/mozilla/puente/blob/4e22c22756cb07b44462ffc7c6a9ec20fc8e572e/puente/commands.py#L201-L223

It may be possible to eliminate the warning by closing ``domain_pot_file`` before leaving the ``if`` clause. A larger change would be to modify the code to use a context manager.

### PR DESCRIPTION
**Pull request by jwhitlock**
Refactor the ``msgmerge`` call into ``_msgmerge``, and use it inside of a context statement so that the domain POT file will be closed for the English and non-English paths.

This removes the Python 3 warning during tests (fixes #71).

### CODE REVIEW

**Comment by willkg** [comment]
I can't easily test this and I can't tell if this is covered in the Puente tests. What'd you do to verify that it works beyond making sure the warning is gone?

**Comment by jwhitlock** [comment]
I did not manually test it. The existing test is ``TestMergecommand::test_basic``, which exercises the ``en-US``/``en_US`` and non-English branches:

https://github.com/mozilla/puente/blob/4e22c22756cb07b44462ffc7c6a9ec20fc8e572e/tests/test_merge.py#L33-L81

I could probably test this in Kuma in the dev environment. We don't generate ``en_US`` by default (who would need it?), but I could try a before and after. Kuma is on Python 2.7, so it wouldn't have the warning, but the code should generate the same files.

**Comment by willkg** [comment]
That sounds fine! Thank you!

**Review by willkg — APPROVED** [review]
This looks good to me. It's a nice refactoring. I probably should have written it this way originally.

enmerge... Srsly.

**Comment by jwhitlock** [comment]
I tried this out:

1. Generated the ``en_US`` locale (``./manage.py merge --create``)
2. Installed this branch
3. Made a trivial manual change to the ``django.pot`` file
4. Ran ``./manage.py merge again``

The trivial change was merged (with a ``#, fuzzy`` marker) to the ``en_US`` file as well as the other locales.

**Pull request merged**
