### PR TITLE
Flesh out jingo

### PR DESCRIPTION
**Pull request by willkg**
r?

### CODE REVIEW

**Comment by willkg** [comment]
@robhudson This fixes some minor issues with Puente to make it and Jingo and Django all work together. It also includes a crucial monkeypatch which I think is the missing thing that's causing you all your problems with MDN.

Let me know if this helps and/or if we need to make changes here to make it better.

**Comment by willkg** [comment]
^^^ Fixes the filename, updates the README and adds a section to the tower migration docs about installing gettext/ngettext into the jinja env.

**Comment by willkg** [comment]
@robhudson Does this look good?

**Comment by robhudson** [comment]
I think this all looks good and again solved my issue. \o/

**Pull request merged**
